### ISSUE TITLE
Dracula crashes on Vs. Screen

### ISSUE THREAD

**Issue by MetalGearPearl** [NemesisSSBU/Playable_Bosses#12]
I really like this mod, but every time I choose Dracula (either to fight him or as him) the game freezes on the Vs screen. Is there anything I can do?

And by the way, if I may make a suggestion, I think it would be great if each boss has the logo of the next franchise (ex. Ganon with the Zelda logo, Marx with Kirby's)

**Comment by NemesisSSBU** [comment]
I’ve been trying for the past hour to freeze the game as Dracula and I have yet to succeed in doing so. Under what conditions did the game freeze when playing as or against Dracula?

Also the suggestion of the franchise logos changing based on what game the boss is from is such a good idea that I just changed the code to do just that.

Thank you for downloading!

**Comment by MetalGearPearl** [comment]
For some reason the game just crashes on the vs screen, it doesn't matter which characters I choose, Dracula always freezes, maybe I have some file conflicting, I'll check thath

**Comment by MetalGearPearl** [comment]
Hello again, I don't know what it could be, I deleted a file that changes Dracula's sounds thinking that this would be the problem but no, the game keeps freezing on the Vs Screen when choosing Dracula

**Comment by NemesisSSBU** [comment]
After some extensive testing, I'm assuming something code wise has been happening that's similar to another [issue reported](https://github.com/NemesisSSBU/Playable_Bosses/issues/13). In this upcoming update that should be out in about 30 minutes, the way Dharkon, Galeem, and Dracula spawn in will be changed in order to potentially fix these issues.

Let us know if the issue still persists after this update.

**Comment by MetalGearPearl** [comment]
Of course, thanks a lot, I'll check that
