### ISSUE TITLE
Ideas and help to coding to the Best bosses or another thing

### ISSUE THREAD

**Issue by RPTOR914** [NemesisSSBU/Playable_Bosses#2]
fixed, nemesis please let me help you know how to install the others, I know but the others don't

**Comment by MaymonAdir** [comment]
Wait how did you install this? Mine crashes

**Comment by RPTOR914** [comment]
I already fixed it, I'm sorry for asking you the question, I don't know if Nemesis will let me show the requirements or not in the mod, but I know them

**Comment by MaymonAdir** [comment]
Anyways, do you have a Discord?

**Comment by RPTOR914** [comment]
yes i have discord my username is RAPTORMASH746#4804

note: i spanish for any message me and i slow writting

**Comment by RPTOR914** [comment]
thanks to the creator of the mod for testing the mod, it's good but bugged and I like that

**Comment by NemesisSSBU** [comment]
I was not aware of this issue. @RPTOR914, thank you for opening this thread and always feel free to show requirements and fix mistakes me and GamerSubzero made.

**Comment by zm1868179** [comment]
I was testing out and can't seem to get it to work. I tried Claudes original release since he was the one who originally made playable bosses.

I have the latest version of Acropolis installed along with the latest skyline version but added this mod causes a crash on game startup. is there something that needs to be done to make this work?

**Comment by NemesisSSBU** [comment]
> I was testing out and can't seem to get it to work. I tried Claudes original release since he was the one who originally made playable bosses.
> 
> I have the latest version of Acropolis installed along with the latest skyline version but added this mod causes a crash on game startup. is there something that needs to be done to make this work?

Hey @zm1868179, thank you for checking the mod out!

Make sure you're up to date with the latest release of ARCropolis and you have libacmd_hook.nro and libnro_hook.nro in the same folder as libcomp_boss.nro (this would be *SD Card Root* --> atmosphere --> contents --> 01006A800016E000 --> romfs --> skyline --> plugins --> *drag and drop .nro files here*).

Also, I would like to point out skyline has been updated and the version put into this mod is outdated. This could potentially be causing the issue(s) and will be fixed in the next build that'll release in the next few weeks. I recommend downloading the latest version of [Skyline](https://github.com/skyline-dev/skyline/releases/tag/beta) and replacing those files (this would be *SD Card Root* --> atmosphere --> contents --> 01006A800016E000 --> exefs --> *main.npdm and subsdk9*).

Hope this helps and happy modding!

**Comment by zm1868179** [comment]
@NemesisSSBU  looks like i was missing the libacmd_hook.nro that was all i was needing looks like th emod loads now so i can try it out

**Comment by NemesisSSBU** [comment]
Nice @zm1868179!

Also, I just pushed out a new build that'll include these files for future downloads and the latest ARCropolis support.

Let us know if anything changes!

**Comment by RPTOR914** [comment]
Hello everyone, I would like to improve your version of the mod, but there is one thing that never works for me, which is the fireshot and the homing shot that dracula stays static and I try to change but I can't. If you can help me, please, in the code, I will I give nemesis name credits (i try to help to playable bosses work better)

**Comment by NemesisSSBU** [comment]
> Hello everyone, I would like to improve your version of the mod, but there is one thing that never works for me, which is the fireshot and the homing shot that dracula stays static and I try to change but I can't. If you can help me, please, in the code, I will I give nemesis name credits (i try to help to playable bosses work better)

Of course, everyone is always free to improve this mod and correct our mistakes (because I know there are a ton of them lol) and we embrace changes with open arms. Dracula is definitely a strange character with complex code which is why we hated dealing with him and Rathalos. Eventually we'll get around to fixing them as they are busted characters at heart.

**Comment by RPTOR914** [comment]
Ok thanks but i already fixed the Dracula2 shot and i try to make another assist tropy or poke playable but it's hard, thanks You, but the rathalos i try to fix the landing and change mode air

:)
