### ISSUE TITLE
WoL Master Hand's neutral B is broken

### ISSUE THREAD

**Issue by MetalGearPearl** [NemesisSSBU/Playable_Bosses#23]
I love playing as WoL Master Hand, but the problem is that its neutral B (or at least charged) causes more than 230% damage, the original Master Hand does not have that issue, only WoL MH

And by the way, how can I export the lib.css things I modified to Smash? I changed the bosses' order in the CSS and I don't know how to see the changes ingame, and also, where can I change the bosses' HP?

**Comment by NemesisSSBU** [comment]
WOL Master Hand has a super powerful default damage multiplier which I think I forgot to set his item power multiplier to match with a lower damage power. This will be fixed in full release.

You can change a boss’ HP by scrolling down to the comment that says “// DAMAGE MODULES” and scroll a little more to the line of code that looks like this: if DamageModule::damage(module_accessor, 0) >= 399.0 {…}

Depending on the character you’re looking at it’s their default HP minus 1. In this example I’m looking at a character with an HP of 400 and all you’d need to do is change that number to your desired number.

Also, the way you’re able to export the lib.rs file is that you must download the entire src folder from GitHub (I think you did since you’re talking about also changing boss HP). In the folder where the src folder is located (not within the src folder itself but the one containing the src folder), open a CMD prompt or terminal in that folder and run the command: Cargo skyline package

After running that command you should have a target folder generated and a release.zip file should exist within it, which holds a new libcomp_boss.nro file.

I hope this helps!

**Comment by MetalGearPearl** [comment]
Thanks for that

Oh, and I ran the command but I got an error message, like this
ObjectNotFound: (Cargo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by NemesisSSBU** [comment]
Make sure you have cargo skyline installed by running this in your command prompt: cargo install cargo-skyline

**Comment by MetalGearPearl** [comment]
I tried that but i got this message:
"cargo" is not recognized as an internal or external command, program, or executable batch file.

**Comment by NemesisSSBU** [comment]
Nice!

**Comment by MetalGearPearl** [comment]
Hi again, I have been trying to download the skyline-cargo but despite having installed what is necessary, now the download is canceled in a certain part, do you know if there is an alternative way to install it or compile the playable bosses folder's changes in another way?

**Comment by NemesisSSBU** [comment]
Hmm, that's strange the skyline download is canceling. Have you tried following the steps within [PiNE's modding guide](https://docs.google.com/document/d/1y_JX5LNsQ8jUBfrghRkL8VkvfMWUIXSrrscM5qj7s6U/edit)? It could be that you don't have [Git](https://git-scm.com/downloads) installed which is needed to download skyline-cargo

**Comment by MetalGearPearl** [comment]
Oh, I have Git installed, but I haven't readed PiNE's guide, I'll check it out

**Comment by MetalGearPearl** [comment]
Sadly, the problem has not yet been solved... After some hours I have continued with the same problem. I have read the guides and my problem is this when installing Skyline:
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/4d9a557d-06dc-4459-afe0-c5404569897e)
I'm not sure what's the problem

Sorry for bothering

**Comment by MetalGearPearl** [comment]
Hi there, sadly I couldn't install cargo skyline, I asked for help but I didn't find something useful

And btw, do you use discord or something to keep in contact?

**Comment by NemesisSSBU** [comment]
That's very strange. Do you have C++ redistributables installed? I unfortunately don't use Discord all too often but my tag on there is "nemesis69"

**Comment by MetalGearPearl** [comment]
In theory, yes, I have everything installed correctly, but if not, how can I check?

**Comment by NemesisSSBU** [comment]
You should be able to check by seeing if the command "cargo skyline help" works (don't include to quotes). This should give a list of commands but if it throws out an error, it should say something like nightly needs to be installed or some program that's missing for the command to work. Also, what types of errors is cargo CMD giving?

**Comment by MetalGearPearl** [comment]
The errors are the following:
When installing cargo-skyline:
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/bd6cdcda-e558-4fe7-9d34-fbc0fa85b2a4)

After typing "skyline-help"
error: no such command: `skyline-help`

**Comment by MetalGearPearl** [comment]
It's pretty strange since I hadn't problems when installing Rust and Git

**Comment by NemesisSSBU** [comment]
Oh I see. I think you need to run your CMD Prompt with administrator privileges since it says the cause is "Access denied".

**Comment by MetalGearPearl** [comment]
I ran it with admin privileges, but the problem persists ;(
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/0f295a2d-8901-4849-af7e-1a7e77bbcf4d)

**Comment by NemesisSSBU** [comment]
Have you tried running these commands in order?:

rustup update

rustup default nightly

cargo install cargo-skyline

I tried on a virtual machine and I wasn't able to replicate that issue

**Comment by MetalGearPearl** [comment]
I just did that, but now this problem appeared
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/a2577614-39b4-4abf-97df-b2af9e6812d2)

**Comment by NemesisSSBU** [comment]
This could actually be a case of windows security being wonky since this is more related to a OS block than a Cargo issue.

You can add an exclusion to your Microsoft Windows defender by going to Virus & Threat Protection, then scroll down to Virus & Threat Protection settings, click on the "Manage Settings" button, scroll to the bottom and it should say "Exclusions". Click on "Add or remove exclusions". Then add an exclusion from the file path which would be the Temp folder in %appdata% folder.

Or you might have a strict anti-virus that isn't windows security (Norton, or Avast or some type of virus protection), just disable it for about 15 minutes or until skyline finishes installing.

Or if that doesn't work you might have a Visual Studio Code's terminal trying to do the same thing while trying to do a cargo run in powershell

**Comment by MetalGearPearl** [comment]
I'm not sure what could it be, I uninstalled VS Code yesterday and just excluded %appdata% on the anti-virus but there aren't changes 
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/137255015/c2c23996-92b1-476f-8908-67c6d5e6340e)

**Comment by NemesisSSBU** [comment]
That's really strange since the error is an OS error. I was looking at this [Reddit post](https://www.reddit.com/r/rust/comments/ep40kb/access_denied_error_out_of_nowhere/) and they're saying about the same things I've said. The only possible this I can think of is that you have an anti-virus enabled which is flagging some of the things Cargo is downloading as a threat.

But I did just search up [this into google](https://www.google.com/search?q=caused+by+access+denied+cargo+OS+Error+5) which some methods in the first 6 results might possibly work.

**Comment by MetalGearPearl** [comment]
Hello again, I really don't know what the problem is and I don't know what to do anymore, so in order not to struggle, do you think you can help me by compiling the changes I made? Through Discord I can send you the files and thus not take more time with this to fix it later calmly 😅

**Comment by NemesisSSBU** [comment]
I can compile your code but thing is that's probably not the most optimal thing to do since we've got to get your modding situation sorted out so that way whenever you make code edits all you need to do is the command: "cargo skyline install" then your switch will immediately get the new code edits.

I was actually looking into a little bit more and I learned that OS Error 5 means lack of permissions which can also be caused by installing Cargo from a different account on your PC, which looking at your screenshot you seem to be installing from your computer's Admin account rather than from a user account. This could be the problem. Also you can forcibly remove the entire cargo folder and reinstall to see if that works.

**Comment by MetalGearPearl** [comment]
Well, in those cases I wouldn't know what to do either, since my PC is a single user, me, and about the Cargo file, are you talking about the one found in the Temp folder? Because I have several folders there with the cargo name but I can't delete them properly because they ask me for administrator permissions to do so

**Comment by NemesisSSBU** [comment]
Oh there's the problem, for some reason your don't have administrator permissions in general. You'd need to pretty much follow [this video](https://www.youtube.com/watch?v=RE3dYzH1CgI&ab_channel=ReyzGamingChannel) to delete the files then reinstall. Then once you get the single Temp folder, you can right click it, click on properties then follow [this video](https://www.youtube.com/watch?v=D2qeasLksOE&ab_channel=TechFixIT) to enable administrator permissions allowing Cargo to add things into it.

**Comment by MetalGearPearl** [comment]
Thanks a lot, I'll check it out!

**Comment by MetalGearPearl** [comment]
Sadly, it didn't work 😔

**Comment by NemesisSSBU** [comment]
It definitely something with the permissions of your appdata folder. Maybe you can try to switch the cargo skyline installations to another folder that isn’t within the appdata directory?

**Comment by MetalGearPearl** [comment]
Oh, how can I do that?

**Comment by NemesisSSBU** [comment]
You could do this by redirecting to a different directory by running the command: cargo install --root C:\Rust\.cargo cargo-skyline

This is just an example that would install cargo-skyline to a folder called Rust\.cargo located in the root of your C: drive rather than the regular appdata folder.

**Comment by MetalGearPearl** [comment]
THANK YOU SO MUCH, EVERYTHING WORKED!!!

**Comment by MetalGearPearl** [comment]
Just one question, how can I change the order in the CSS of the bosses?

**Comment by NemesisSSBU** [comment]
Awesome! Also the way you change their display order is by going into the lib.rs file and I labeled each character with a comment such as // Master Hand, // Crazy Hand, etc. Below those comments are hashes and directly editing the PRC through code edits which is unusual but that’s how this mod works. What you’re looking for is editing the display value settings so look for the line of codes that say: if *hash == to_hash40("disp_order") {

below that hash if statement you should edit the number value to the position you want that character to be displayed in on the CSS
