### ISSUE TITLE
Add more moves for masterhand/crazyhand

### ISSUE THREAD

**Issue by cheetahsbdf** [NemesisSSBU/Playable_Bosses#24]
Could you add the partner attacks that both master hand and crazy hand have? Potentially make it possible to have them do these attacks when they are on the same team. Some attacks are the finder attack, the bark attack, and electroshock. This would be a great feature! I couldn't get it to work myself. (Crazyhand refuses to initiate the attack and just switches to another one) I hope this can be made!

**Comment by NemesisSSBU** [comment]
This is what we were originally going for but then I kind of forgot about it. This should be possible to implement it and if I find a way, you bet it’ll be implemented in the full release since I really like this idea!

**Comment by cheetahsbdf** [comment]
Nice! Can't wait! From my attempts, I got masterhand to initiate the bark attack, yet crazyhand won't initiate it. I believe crazyhand is the important part to this because he controls the sound, effects, and the ability to cause damage. Masterhand does nothing but the animation when the status is changed.

**Comment by NemesisSSBU** [comment]
Finally figured it out. Master Hand and Crazy Hand will now have duet moves in the full release!

**Comment by NemesisSSBU** [comment]
https://github.com/NemesisSSBU/Playable_Bosses/assets/88991848/0f9bee5f-d772-4824-8773-320f25d63113

**Comment by cheetahsbdf** [comment]
Amazing! How do you trigger them both to do the attack?

**Comment by NemesisSSBU** [comment]
A lot of checking when animations do their frames and ending frames along with settings Crazy Hand to do those moves by doing something like this:

                    if BARK && !DEAD_2 && MASTER_EXISTS && MotionModule::motion_kind(boss_boma_2) != smash::hash40("bark") && CRAZY_USABLE {
                        MotionModule::set_rate(boss_boma_2, 1.0);
                        smash::app::lua_bind::ItemMotionAnimcmdModuleImpl::set_fix_rate(boss_boma_2, 1.0);
                        CONTROLLABLE_2 = false;
                        StatusModule::change_status_request_from_script(boss_boma_2, *ITEM_CRAZYHAND_STATUS_KIND_DEBUG_WAIT, true);
                        MotionModule::change_motion(boss_boma_2,Hash40::new("bark"),0.0,1.0,false,0.0,false,false);
                    }
                    
Crazy Hand is only able to do team attacks when it goes through a change_motion rather than an item status

**Comment by cheetahsbdf** [comment]
Cool! What buttons trigger the attack in game?

**Comment by NemesisSSBU** [comment]
In the beta it isn’t a thing but on the full release they will be assigned to:

Jump button on Crazy Hand = team punch, Jump button on Master Hand = stage shock, DPAD UP on Master Hand = bark attack
DPAD UP on Crazy Hand = death range shrink

**Comment by cheetahsbdf** [comment]
Awesome! I was just thinking of asking for the FINDER attack. Glad you already thought of it. What will you do for the other attacks that had those button attachments? Also, could you tell me where to find a list of buttons? When I see "FIGHTER_PAD_CMD_CAT1_FLAG_ATTACK_HI3" I have no idea what it connects to on my controller. I would love a list so I can customize the attacks for my personal use. One more thing, is this locked? if I do the jump button on master hand, will it auto-initiate the attack for crazy hand as well? Same thing for the bark attack. Thanks so much for this!!

**Comment by cheetahsbdf** [comment]
Also, do you have plans to introduce the boss intros? Not really needed but if possible and you have some free time, it would be another nice feature

**Comment by NemesisSSBU** [comment]
If either Master Hand or Crazy Hand initiate their attacks, it’ll check if other hand is facing the correct direction and if they’re idle. If both come back true, both hands will go into their team attack animations.

Also, I didn’t find a full on list for the controls so I just made a quick little list:

CONTROL_PAD_BUTTON_JUMP // X and Y buttons

CONTROL_PAD_BUTTON_ATTACK // A button

CONTROL_PAD_BUTTON_SPECIAL // B button

CONTROL_PAD_BUTTON_GUARD // Trigger buttons

FIGHTER_PAD_CMD_CAT1_FLAG_SPECIAL_LW // Special button + left analog stick facing down

FIGHTER_PAD_CMD_CAT1_FLAG_SPECIAL_HI // Special button + left analog stick facing up

FIGHTER_PAD_CMD_CAT1_FLAG_SPECIAL_S // Special button + left analog stick facing left or right

FIGHTER_PAD_CMD_CAT1_FLAG_ATTACK_LW3 // Attack button + left analog stick facing down

FIGHTER_PAD_CMD_CAT1_FLAG_ATTACK_HI3 // Attack button + left analog stick facing up

FIGHTER_PAD_CMD_CAT1_FLAG_ATTACK_S3 // Attack button + left analog stick facing left or right

CONTROL_PAD_BUTTON_APPEAL_HI // DPAD Up

CONTROL_PAD_BUTTON_APPEAL_LW // DPAD Down

CONTROL_PAD_BUTTON_APPEAL_S_R // DPAD Right

CONTROL_PAD_BUTTON_APPEAL_S_L // DPAD Left

I did try to do entry camera animations for bosses and they didn’t work out too well due to how quickly the boss animations enter (on purpose so they aren’t doing their entry animation while the match has already started)

**Comment by NemesisSSBU** [comment]
They have been given their team abilities in the [full release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
