### ISSUE TITLE
Question: How do I add multiple items?

### ISSUE THREAD

**Issue by cheetahsbdf** [NemesisSSBU/Playable_Bosses#26]
Looking to add multiple items

ITEM_KIND_MASTERHAND
ITEM_KIND_CRAZYHAND 

Master hand loads but Crazy hand does not. I am interested in two items being loaded over one fighter instance

**Comment by NemesisSSBU** [comment]
Master Hand and Crazy Hand are separate characters that load when their respective slots are chosen. This means you’d have to choose both Master Hand and Crazy Hand if you want them to both spawn in.

The reason they’re combined in the files of this mod is because that’s the only easy way we figure of sharing duet move information between the two.

If you wanted to edit the code to spawn in Crazy Hand at the same time master hand loads in you can take the entire lines of 1652-1659 on the mastercrazy file and put it into the time Master Hand spawns in at lines 155-163.

But keep in mind I’d recommend keeping them separate as it’d be difficult controlling two hands at the same time given you’d have to instead use what the console reads for input information rather than what Smash reads. Also combining both Master Hand and Crazy Hand in the same fighter would create a bunch of issues in general such as HP conflicts, controllability, and conflicting fighter information.

**Comment by cheetahsbdf** [comment]
ah, okay. Thanks!

**Comment by cheetahsbdf** [comment]
It seems like it didn't add master hand. IT now only adds crazy hand even though I never replaced it. I see what you mean by issues. I just wanted to create master hand & crazy hand as seen in classic mode. I was fine having them have the same inputs.

**Comment by NemesisSSBU** [comment]
Oh, in that case you can try experimenting with flags and item variation such as *ITEM_VARIATION_MASTERHAND_CRAZYHAND_STANDARD.

The way you would apply this is by doing something like: 

WorkModule::set_int(boss_boma, *ITEM_VARIATION_MASTERHAND_CRAZYHAND_STANDARD, *ITEM_INSTANCE_WORK_INT_VARIATION); // For Master Hand

WorkModule::set_int(boss_boma_2, *ITEM_VARIATION_CRAZYHAND_MASTERHAND_STANDARD, *ITEM_INSTANCE_WORK_INT_VARIATION); // For Crazy Hand

I've also been trying to pair them up like that but failed to replicate the regular boss battle connection.

**Comment by cheetahsbdf** [comment]
ah, that's a shame. also neither of these did anything for me, I might be putting them in the wrong spot. I placed it under ITEM_KIND_MASTERHAND and for crazy hand respectively

**Comment by NemesisSSBU** [comment]
They didn’t do anything for me either but I figure they’re major parts in getting true linked bosses since bosses that don’t have a partner don’t have specific variation statuses.
