### ISSUE TITLE
Disabling mod through ARCropolis crashes upon loading character select screen.

### ISSUE THREAD

**Issue by CaptainGame17** [NemesisSSBU/Playable_Bosses#29]
If you disable the playable bosses mod through the eShop mod manager (which is built into ARCropolis,) the game will crash upon trying to load the character select screen.

**Comment by NemesisSSBU** [comment]
Thank you for telling us about this issue. Unfortunately this is out of our reach since both of the files found when downloading this mod (the .nro files and the Bosses mod folder), are required to be loaded together (with the exception of the Bosses mod folder not existing). If the libcomp_boss.nro file is disabled while the Bosses mod folder is still loading in, many issues can occur, ranging from instant crashes to random freezes when opening the character select screen. The best solution to this is to have both the libcomp_boss.bro and Bosses mod folder enabled when using the mod and when you’re done with the mod, disable the entirety of the mod by scrolling to ARCropolis’ mod enable/disable section, then somehow through ARCropolis disable the Bosses mod folder or just manually remove it.
