### ISSUE TITLE
Bosses on WOL CSS [Possible Enhancement?] 

### ISSUE THREAD

**Issue by zm1868179** [NemesisSSBU/Playable_Bosses#3]
Over a year ago I was playing around with Claudes Playable Bosses files that this was based off of and had managed to get the Bosses added to the CSS Screen in WOL by making edits to the ui_chara_db.prc. 

If I remember correctly, I had to swap an existing Character on the WOL CSS Screen with a Boss Such as the Mii Fighters along with making them visible. I currently have 2 save slots on my WOL that one has Master hand, and another has Crazy hand from way back then Using this mod makes them they load correctly and function without crashes. It seems this mod fixes some issues with the bosses loading into the WOL Maps and battles. That I had experienced all that time ago. 

This version of the mod seems to edit the Character DB for the CSS directly by the plugin rather than a file swap and it seems to set the correct parameters. is it possible through the plugin to expand the WOL CSS and add them to that entry as well They can currently be loaded by edizon memory editing but having them on the CSS in WOL would be easier.

**Comment by NemesisSSBU** [comment]
We were actually looking into this for a very long time and thinking about making it so you unlock each boss character in WOL after their first battle interaction. But some issues came out of this at the time since we weren't so sure how to implement this. Now since we're more knowledgeable, we probably can implement something like this, but only after startup most likely as this is when the CSS gets edited.

Or we can actually set it to have all the bosses unlocked immediately on the WOL CSS (honestly I thought this was already implemented but I must've forgotten to change it from when we were testing unlockable bosses lol).

**Comment by zm1868179** [comment]
that sounds awesome. Yea I got the mod loaded up and hoped into one of my WOL saves where I had edited my character to be master hand and it loaded up with the model actually the correct size and over the marker where the player would be.

With Claudes original mod this worked. If I managed to get him on the CSS Screen, I could select him, and it would load but with his original mod the model for master hand was gigantic and stuck in the middle of the WOL Map and didn't follow the players cursor the map just had a shadow on the map that moved around this version of the mod seems to correct that now.
