### ISSUE TITLE
There is missing many worlds of dlc

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#42]
Hi i see is missing many stage of dlc and there are no stage of kazuya, Pyra and Mythra, Sepiroth And Sora. Can you please add this stages??

**Comment by NemesisSSBU** [comment]
I believe this is because you own the DLC’s but the boss stages that this mod puts in pushed those DLC stages to the side. This is why I put 2 extra alternative downloads that get rid of either a couple or all the maps, restoring the extra DLC maps but at the cost of not having those extra boss stages, this is able to be downloaded in the regular [download section](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)

**Comment by SwitchAdventurer** [comment]
Oh ok thank you for telling me
