### ISSUE TITLE
When Galeem and Dharkon do the move that create the exploding CPU character only one comes out instead of three and sometimes the CPU doesn't appear

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#45]
The original boss of Galeem and dharkon when do the move who create the bot character and exploding they bring out three and not one but the Galeem and Dharkon playable create only one bot to explode and sometimes the CPU doesn't appear

**Comment by NemesisSSBU** [comment]
This is something I wish I could fix but unfortunately when Dharkon and Galeem summon bosses, they’re summoning fighter’s I can’t really do anything about. I’m wondering if I can summon a single fighter and actually make them controllable in order to compensate for the lack of the other two fighters (or no fighters sometimes).
