### ISSUE TITLE
There's no Atmosphere folder?

### ISSUE THREAD

**Issue by USSaRbys** [NemesisSSBU/Playable_Bosses#5]
I'm very new at this so I could just be missing something very obvious, but there's no folder for atmosphere in the zip and I have no idea what to do with the rest of the files. I've tried many different things, but nothing seems to work.

**Comment by AizerMortenort** [comment]
the author seems to have abandoned the mod project. He doesnt reply to issues.

**Comment by USSaRbys** [comment]
That's a shame, thanks for letting me know.

**Comment by NemesisSSBU** [comment]
> the author seems to have abandoned the mod project. He doesnt reply to issues.

We do reply, it just takes awhile as we usually don't log into GitHub all too often.

> That's a shame, thanks for letting me know.

Welcome to the Smash modding community! Atmosphere is a type of "Homebrew" application that launches when you inject specific files in after the [Hekate](https://github.com/CTCaer/hekate/releases) payload is injected into system startup. A Gen 1 Nintendo Switch is required in order to boot up with Hekate and a paperclip slider into the right hand side joystick slot while booting up. But before you boot up into the mod menus, load your micro SD card with [atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases). With atmosphere and after it's initial boot, you can launch Smash and a smash folder should be created within the atmosphere folder (should be located in: atmosphere -> content -> 01006A800016E000). You can shut off your Switch, plugin your micro SD card back into your computer, drag and drop all the mods you want into the atmosphere (our boss mod should be immediately draggable and droppable into the root of the SD card). Make sure you have [ARCropolis](https://github.com/Raytwo/ARCropolis) installed into your atmosphere folder (drag these folders into: atmosphere -> content -> 01006A800016E000). Eject your micro SD card, plug it into your switch, reinject Hekate's payload, and you should be smooth sailing from there.

Modding might sound tedious and complex at first but it truly is a gateway into a whole new video game world and I couldn't recommend it enough as it opens up various creative opportunities and endless experiences that will never become stale.

Sorry for the late response, we are still here.
