### ISSUE TITLE
Bosses Character Select Screen Slot Invisible

### ISSUE THREAD

**Issue by SonicCD2025** [NemesisSSBU/Playable_Bosses#52]
Each of the bosses slots on the character select screen are invisible. Their render shows down where it says P1, P2 etc., but the slot you select them with is invisible. Is there a way to fix that?

**Comment by NemesisSSBU** [comment]
Can you post a screenshot, I’m not quite understanding. But if it’s what I think it is, are the icons of the boss CSS missing? If so, be sure the Bosses mod folder is located in ultimate —> mods —> (drag here). If it is, there could be conflicting files from other mods, perhaps a .json file that is overriding some changes (perhaps if you downloaded Claude’s version of playable bosses but didn’t fully delete it).

**Comment by SonicCD2025** [comment]
Apologies for not explaining very well! Here's a picture:

I have a character select mod turned on, and although it added extra slots for the bosses, the bosses' icons are invisible. They don't know up in battle either. But the render shows up where it says "P1" and on the match loading screen.

![IMG_8245](https://github.com/NemesisSSBU/Playable_Bosses/assets/141853133/6acd4993-a153-4c3f-9016-e5049f4907c2)

**Comment by NemesisSSBU** [comment]
What CSS mod is that? I’ve tested with a couple and they loaded the boss portraits but it could be specific to that mod (potentially).

**Comment by SonicCD2025** [comment]
It's the Mural/Banner Hex CSS Pack mod. It's very cool. Here's the link: https://gamebanana.com/mods/419302

It might be specific to the mod, I'm just trying to figure out a way to get it to work so I can have a cleaner looking character select menu.

**Comment by NemesisSSBU** [comment]
![Screenshot 2023-08-09 145536](https://github.com/NemesisSSBU/Playable_Bosses/assets/88991848/c135b0e7-ada6-4435-93a7-fd657d62b58f)

Hmm. I did some adjusting on the CSS screen since it goes over the 91 css limit but the icons still show. I think you might have another conflicting mod or possibly your Bosses mod folder isn't loading. How does your Mod folder look?

**Comment by SonicCD2025** [comment]
The Mural/Banner Hex CSS Pack mod comes with two different CSS layouts. One is Banner, the other is Mural. It seems you're using Banner. I'm using Mural and that's where my issue is. Can you try using Mural and let me know if the bosses' icons show up there too? 

What adjusting did you need to do on the CSS screen?

My mod folder is jam packed with mods. I wouldn't know where to start if one was conflicting with it. There are no conflicts detected by Acropolis so I'm not sure what to look for. 

Everything in the bosses folder is as it should be except layout.arc for char_select, which I removed because it conflicted with the layout.arc for the Hex CSS mod.

<img width="1022" alt="Mod Folder" src="https://github.com/NemesisSSBU/Playable_Bosses/assets/141853133/c92c4bc3-ea13-48df-965b-fdbc87543522">
<img width="1022" alt="Plugins" src="https://github.com/NemesisSSBU/Playable_Bosses/assets/141853133/12d240e3-472c-44db-8b66-fec0c51de219">
<img width="1022" alt="Bosses Folder" src="https://github.com/NemesisSSBU/Playable_Bosses/assets/141853133/cc231421-2119-4f5e-8c20-b5e008a7b8f7">
 Mod

**Comment by NemesisSSBU** [comment]
![Screenshot 2023-08-09 161558](https://github.com/NemesisSSBU/Playable_Bosses/assets/88991848/9d7a0957-825d-4f56-9a71-1b011ea95611) (Ignore how there's only 4 bosses, I didn't put CSK's modifications on it yet)

It's definitely due to a confliction within one of those mods in that case. I don't think the CSS Mural mod you have would do any of that, could be one of the smaller mods that conflict with some config.json file and has a bit of a domino effect. But having that many mods installed and having this mod, that's going to require some digging.

**Comment by SonicCD2025** [comment]
Gotcha, thanks! I'll do some digging into the config.json files in my mods folder and see what I can find. Is there anything specifically I should look out for that would cause a conflict like this?

**Comment by NemesisSSBU** [comment]
My best guess would be that there's something in a config.json file that overrides the "ui/replace/chara/chara_2", "ui/replace/chara/chara_4", etc. which renders the replace --> chara files as impossible to do anything with since there's no such thing as, for example, chara_4_marx_00.bntx within vanilla smash, therefore we'd need the config.json file to open up a slot for it within the game files but something is blocking that from happening.
