### ISSUE TITLE
Sora problem

### ISSUE THREAD

**Issue by MaymonAdir** [NemesisSSBU/Playable_Bosses#53]
The mod is fabulous but I can't hear the announcer say "Sora!" when I select him.
What's the reason for this?

**Comment by NemesisSSBU** [comment]
That completely skipped our minds. This mod started development a little over 2 years ago. One of the first things we changed was the announcer audio file but this announcer file didn’t get updated in about 2 years, missing Sora and a couple other DLC’s.

**Comment by MaymonAdir** [comment]
Only "Sora" doesn't work right now. Is there anything to fix it?

**Comment by NemesisSSBU** [comment]
Yeah this would require a whole remake of the audio since this mod was in development before Sora released. This stems from the soundlabelinfo.sli file not having Sora's announcer voice line and this would mean I have to extract the new .sli file and redo all the boss audio clips. Unfortunately this would take a decent amount of audio editing and file transfers as I no longer have those audio clips so for now Sora's announcer voice line will have to remain cut.
