### ISSUE TITLE
No libcomp_boss.nro file?

### ISSUE THREAD

**Issue by tresequ1s** [NemesisSSBU/Playable_Bosses#7]
I can't seem to locate the libcomp_boss.nro Skyline plugin file required for this mod to properly work. Any updates?

**Comment by NemesisSSBU** [comment]
Hey there,

The libcomp_boss.nro file is located within the release.zip file that is found within the Releases section on GitHub. [Here's the latest version](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.7-Fix) and that specific file can be found in atmosphere --> contents --> 01006A800016E000 --> romfs --> skyline --> plugins --> libcomp_boss.nro.

The two folders found upon opening the release.zip folder are meant to be dragged and dropped into the root of your SD card for convivence.

I hope this helped and enjoy the mod!

**Comment by tresequ1s** [comment]
It worked! Thank you so much, and I highly appreciate your time and attention towards this matter.

**Comment by NemesisSSBU** [comment]
> It worked! Thank you so much. However, it seemed to have specifically removed Joker, Hero, Terry, Byleth, Min Min, Sephiroth, and Sora. Is this part of the mod or is there any way to fix this issue?

Glad to hear it worked!

But unfortunately you are correct that those character are intentionally removed within this mod. This is to ensure the Character Select Screen doesn't exceed 91 character slots or else the entire CSS will bug out and all characters will be put into a single column, making it impossible to select most characters and the easiest workaround we thought of was to remove some DLC characters.

If you would rather remove some other characters instead of the DLC characters, the ability to do so can be found [here](https://github.com/NemesisSSBU/Playable_Bosses/blob/main/src/lib.rs). I made some comments regarding where the characters that were removed are located in the comment that says "//Remove DLC's (aka get the CSS down to 91 characters)". There are 7 functions that call to the DLC characters and set their display to -1, but all you would have to do is replace the "ui_chara_[INSERT CHARACTER CODE NAME]" part of the code for each function. It may seem intimidating at first but recompiling the mod with those specific modifications will bring back the DLC.

Or maybe instead of going through the hassle of that, should I hide echo characters instead of DLC characters?

**Comment by tresequ1s** [comment]
Hey there again,

I believe I will keep the mod as is, seeing that I am lucky enough to have 2 SD cards (haha).
Should I find any characters that deserve to be removed over the ones who already are, I will be sure to let you know. As always, thank you for your responses, and thank you for the mod!

**Comment by NemesisSSBU** [comment]
No problem!

We're probably going to swap the removal of DLC characters for the echo fighters in the near future since it seems people well... want their DLC that they rightfully bought.

Happy modding!
