### ISSUE TITLE
Sephiroth and Sora are missing from the CSS

### ISSUE THREAD

**Issue by PSISeven** [NemesisSSBU/Playable_Bosses#8]
I have no other CSS mods enabled (of course). This is only an issue when I have the libboss_comp.nro plugin. This applies to both the regular CSS and for World of Light.

**Comment by NemesisSSBU** [comment]
> I have no other CSS mods enabled (of course). This is only an issue when I have the libboss_comp.nro plugin. This applies to both the regular CSS and for World of Light.

This mod unfortunately has to knock down the character count to 91 on the CSS. We're planning on rather than removing DLC fighters to do this, instead we will remove echo fighters from the CSS.

Sorry about the mod limits but Nintendo made a hard CSS cap and exceeding it will result in a broken CSS screen.

**Comment by NemesisSSBU** [comment]
Finally fixed thanks to CoolSonicKirby's CSS limit remover!
